Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date] = '%m/%d'
Time::DATE_FORMATS[:time] = '%H:%M'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'
Date::DATE_FORMATS[:eng] = '%a/%d%Y'
